### PR TITLE
fix: Reload data after bulk update

### LINKED ISSUE #7296: 🐛 Bug: select multiple cells, clear - related formula column's data doesn't reload automatically
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- CONCAT({Title}, " something")
- Select multiple cells in {Title} field, clear
- Formula display field doesn't get updated immediately. Needs a page reload

### Desired Behavior

Formula fields should immediately reflect new change

### Project Details

202.10

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by pranavxc**
## Change Summary

- Closes #7296 

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [ ] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

### CODE REVIEW

File: packages/nc-gui/composables/useData.ts [hunk 1]
```diff
@@ -403,6 +403,8 @@ export function useData(args: {
       if (row.rowMeta) row.rowMeta.saving = false
     }
 
+    // reload data since row update may change the other columns data( formula, QrCode, Barcode, Rollup, Checkbox, User, Auto Updated Datetime, etc...)
+    await callbacks?.loadData?.()
```
Comment (mertmit) [inline packages/nc-gui/composables/useData.ts:407]: In the block above we try to update those to avoid refreshing all page with every bulk update, isn't it possible to avoid calling this

**Review by dstala — APPROVED** [review]

File: packages/nc-gui/composables/useData.ts (hunk 1 above)
Comment (pranavxc) [reply packages/nc-gui/composables/useData.ts:407]: If there is column which refers to the updated column(eg: Formula, QrCode, Barcode, etc...) it won't reload on clearing the cell. If we are clearing single cell it's updating row using the response data but for bulk update we don't have those information.

Comment (pranavxc) [reply packages/nc-gui/composables/useData.ts:407]: We can skip it when unnecessary by checking presence of any such column

**Review by mertmit — APPROVED** [review]
This is good for now, fixes the issue mentioned.

For future reference:
- We can later switch to silent refresh (page loader comes up every time)
- Also if there is a sort applied this can cause modified columns to reorder to other pages, we need to think about UX carefully on those (one alternative is we can refresh selected rows only with a list call with filtering pk's in array providing our pks)

**Review by dstala — APPROVED** [review]
