### PR TITLE
fix: Links modal pagination

### LINKED ISSUE #6418: 🐛 Bug: linked modal search doesn't work when accessing 2nd page onwards
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

open linked records modal
navigate to second page
searc

### Desired Behavior

search should work

### Project Details

x

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by DarkPhoenix2704**
## Change Summary

Provide summary of changes with issue number if any.
Closes #6418 

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [ ] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

### CODE REVIEW

**Comment by DarkPhoenix2704** [comment]
Closes #6418

File: packages/nc-gui/components/virtual-cell/components/ListItems.vue [hunk 1]
```diff
@@ -202,46 +210,75 @@ watch(expandedFormDlg, () => {
...
+                () => {
+                  expandedFormRow = refRow
+                  expandedFormDlg = true
+                }
+              "
+              @click="
+                () => {
+                  if (isChildrenExcludedListLinked[Number.parseInt(id)]) unlinkRow(refRow, Number.parseInt(id))
+                  else linkRow(refRow, Number.parseInt(id))
+                }
```
Comment (sreehari2003) [inline packages/nc-gui/components/virtual-cell/components/ListItems.vue:264]: dont do this create a separate function for these
