### PR TITLE
fix: color picker realtime update

### LINKED ISSUE #6483: 🐛 Bug: Multi-select custom color is not set
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- [x] When customer color is chosen - it is not set.
- [x] Add 2 options. Save. Add 3rd option - observe the color chosen is same as first one. We should chose the third color instead.

### Desired Behavior

.

### Project Details

.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by sreehari2003**
## Change Summary

- closes #6483

Provide summary of changes with issue number if any.

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [x] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

https://github.com/nocodb/nocodb/assets/66205494/c93a3d10-5952-4d3e-8f6e-364a4c2b2ae2

Anything for maintainers to be made aware of

### CODE REVIEW

File: packages/nc-gui/components/smartsheet/column/SelectOptions.vue [hunk 1]
```diff
@@ -215,14 +215,10 @@ watch(vModel.value, (next) => {
...
-                  <LazyGeneralColorPicker
-                    v-model="element.color"
-                    :pick-button="true"
-                    @update:model-value="colorMenus[index] = false"
-                  />
+                  <LazyGeneralColorPicker v-model="element.color" :pick-button="true" @close-modal="colorMenus[index] = false" />
                 </template>
                 <MdiArrowDownDropCircle
-                  class="mr-2 text-[1.5em] outline-0 hover:!text-[1.75em]"
+                  class="mr-2 text-[1.5em] outline-0 hover:!text-[1.75em] hover:cursor-pointer"
```
Comment (wingkwong) [inline packages/nc-gui/components/smartsheet/column/SelectOptions.vue:221]: `cursor-pointer` is for hover event. please double check if `hover:` is really necessary here.

**Review by dstala — APPROVED** [review]
