### PR TITLE
fix: mutation of row prop

### LINKED ISSUE #6449: Unexpected mutation of "row" prop
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Run lint on `nc-gui`  Errors thrown from `packages/nc-gui/components/virtual-cell/components/ListItem.vue`.

```
  106:78  error  Unexpected mutation of "row" prop  vue/no-mutating-props
  109:26  error  Unexpected mutation of "row" prop  vue/no-mutating-props
```

Introduced in https://github.com/nocodb/nocodb/commit/a988acbfc75fa34ef2a66593aca9274ccb530071#

### Desired Behavior

No mutation of "row" prop

### Project Details

Node: **v18.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
RootDB: **mssql**
PackageVersion: **0.111.4**

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by DarkPhoenix2704**
## Change Summary

Closes #6449

Provide summary of changes with issue number if any.

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [ ] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

### CODE REVIEW

**Review by wingkwong — CHANGES_REQUESTED** [review]
please run lint to check first.

```
Parsing error: Cannot set property index of Error which has only a getter
```

File: packages/nc-gui/components/virtual-cell/components/ListItem.vue [hunk 1]
```diff
@@ -31,10 +33,12 @@ interface Attachment {
   mimetype: string
 }
 
-const attachments: Attachment[] = computed(() => {
+const attachments: ComputedRef<Attachment[]> = computed(() => {
   try {
-    if (attachment && row[attachment.title]) {
-      return typeof row[attachment.title] === 'string' ? JSON.parse(row[attachment.title]) : row[attachment.title]
+    if (props.attachment && props.attachment[props.attachment.title]) {
```
Comment (wingkwong) [inline packages/nc-gui/components/virtual-cell/components/ListItem.vue:38]: the logic is different. why change `row` to `props.attachment`?

Comment (DarkPhoenix2704) [reply packages/nc-gui/components/virtual-cell/components/ListItem.vue]: typo
