### PR TITLE
fix: Auto increment field ID not ignored if sent in API payload

### LINKED ISSUE #5871: 🐛 Bug: Auto increment field `ID` not ignored if sent in API payload
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Issue observed in PG
- Insert a record from API with Auto increment field `Id` set to 1
- Try to insert a new record from UI after this

```
error: insert into "Sheet1" ("SingleLineText") values ('aaa') returning "Id" as "Id" - duplicate key value violates unique constraint "Sheet1_pkey"
    at Parser.parseErrorMessage (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 185,
  severity: 'ERROR',
  code: '23505',
  detail: 'Key ("Id")=(1) already exists.',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'Sheet1',
  column: undefined,
  dataType: undefined,
  constraint: 'Sheet1_pkey',
  file: 'nbtinsert.c',
  line: '663',
  routine: '_bt_check_unique'
}
[Nest] 18736  - 06/12/2023, 4:32:33 PM   ERROR [GlobalExceptionFilter] insert into "Sheet1" ("SingleLineText") values ('aaa') returning "Id" as "Id" - duplicate key value violates unique constraint "Sheet1_pkey"
error: insert into "Sheet1" ("SingleLineText") values ('aaa') returning "Id" as "Id" - duplicate key value violates unique constraint "Sheet1_pkey"
    at Parser.parseErrorMessage (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/Users/rajuudava/NocoDB/nocodb/packages/nocodb/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

### Desired Behavior

Ignore if auto-increment field in API request

### Project Details

v0.108.1

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by aashishagrawall**
closes #5871 

## Change Summary

Auto increment field ID not ignored if sent in API payload

## Change type

 fix: (Auto increment field ID not ignored if sent in API payload)

## Provide summary of changes
 
https://www.loom.com/share/89c0a5269e0a452a84f843cf5eefea39?sid=66202231-bdfe-4f86-8e76-7b85d6926f2c

### CODE REVIEW

**Review by wingkwong — CHANGES_REQUESTED** [review]
This solution only works for `Id` and it is a auto-increment field. Any other auto increment fields with other names or non auto-increment field but named `Id` will fail. 

We have a meta data for each column. One of them is a boolean called `ai` indicating if this column is auto-increment. Hence, the ideal solution would be skipping those `ai = true` columns.

File: packages/nocodb/src/db/BaseModelSqlv2.ts [hunk 1]
```diff
@@ -2193,7 +2193,19 @@ class BaseModelSqlv2 {
         await this.beforeInsert(insertObj, trx, cookie);
       }
 
-      await this.model.getColumns();
+      const columns = await this.model.getColumns();
+
+      // exclude auto increment columns in body
+      for (const col of columns) {
+        if (col.ai === true) {
```
Comment (pranavxc) [inline packages/nocodb/src/db/BaseModelSqlv2.ts:2200]: could be just `if (col.ai) {` since in some cases it will be `1` ( in some database it stored as tinyint(1) )

Comment (aashishagrawall) [reply packages/nocodb/src/db/BaseModelSqlv2.ts:2200]: ok

File: packages/nocodb/src/db/BaseModelSqlv2.ts [hunk 2]
```diff
@@ -2193,7 +2193,19 @@ class BaseModelSqlv2 {
...
+          const keyName =
+            data?.[col.column_name] !== undefined ? col.column_name : col.title;
+
+          if (data[keyName]) {
+            delete data[keyName];
```
Comment (pranavxc) [inline packages/nocodb/src/db/BaseModelSqlv2.ts:2205]: You are just delete=ing it from `data` and not from `insertObj` so still it will insert value.

Comment (aashishagrawall) [reply packages/nocodb/src/db/BaseModelSqlv2.ts:2205]: fixed and tested

**Review by pranavxc — APPROVED** [review]
