### PR TITLE
fix(gui-v2): include host from NC_DB url

### LINKED ISSUE #3529: Handling support for parsing jdbc connection params has affected NC_DB
PG database url is connecting to localhost.

You can downgrade to 0.92.4 for the moment until we make a release today.

### PR DESCRIPTION
**Pull request by pranavxc**
## Change Summary

Fix #3529 

Include the host value provided in the `NC_DB` URL while extracting knex connection config.

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [x] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

### CODE REVIEW

File: packages/nocodb/src/lib/utils/NcConfigFactory.ts [hunk 1]
```diff
@@ -636,54 +642,82 @@ export default class NcConfigFactory implements NcConfig {
...
       const client = driverClientMapping[driver] || driver;
-      
-      const avoidSSL = ['localhost', '127.0.0.1', 'host.docker.internal', '172.17. 0.1']
 
-      if (client === 'pg' && !connectionConfig?.ssl && !avoidSSL.includes(connectionConfig.host)) {
+      const avoidSSL = [
+        'localhost',
+        '127.0.0.1',
+        'host.docker.internal',
+        '172.17. 0.1',
```
Comment (o1lab) [inline packages/nocodb/src/lib/utils/NcConfigFactory.ts:688]: extra space in line number 688

**Review by mertmit — APPROVED** [review]

**Review by wingkwong — APPROVED** [review]

**Review by mertmit — APPROVED** [review]
