### PR TITLE
fix: import various

### LINKED ISSUE #6611: 🐛 Bug: Import CSV from Airtable export with Checkbox column fails
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Using an existing Airtable table make sure there is a checkbox column in the table, and at least one row has value checked
export it to CSV file.

If you review the values in the CSV file you will see the checkbox column in the rows where the checkbox is selected have the data values of "checked"

Import the same file into NocoDB. The import fails with the error: 

```
invalid input syntax for type boolean: "checked"
```

### Desired Behavior

Checkbox columns import correctly. 

There is a workaround, where if you edit the CSV file before importing it, and change the checkbox column values of "checked" to "TRUE", the import works correctly. But you need to remember to update the CSV file before importing it. 

### Project Details

NocoDB version 0.111.4 via docker loading using a Postgres 12 database

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by mertmit**
## Change Summary

Closes #6611 #6465

## Change type

- [x] fix: (bug fix for the user, not a fix to a build script)

### CODE REVIEW

File: packages/nocodb/src/modules/jobs/jobs/at-import/at-import.processor.ts [hunk 1]
```diff
@@ -314,11 +314,11 @@ export class AtImportProcessor {
     const nc_getSanitizedColumnName = (table, name) => {
       let col_name = nc_sanitizeName(name);
 
-      // truncate to 60 chars if character if exceeds above 60
-      col_name = col_name?.slice(0, 60);
+      // truncate to 60 chars if character if exceeds above 50
```
Comment (wingkwong) [inline packages/nocodb/src/modules/jobs/jobs/at-import/at-import.processor.ts:317]: `truncate to 50 chars if character if exceeds above 50`?

File: packages/nocodb/src/modules/jobs/jobs/at-import/at-import.processor.ts [hunk 2]
```diff
@@ -328,13 +328,31 @@ export class AtImportProcessor {
...
+      }
+      if (duplicateColumn) {
+        let iterator = 1;
+        while (
+          table.columns.find(
+            (x) =>
+              x.column_name?.toLowerCase() ===
+              `${col_name}_${++iterator}`?.toLowerCase(),
+          )
+        ) {}
```
Comment (wingkwong) [inline packages/nocodb/src/modules/jobs/jobs/at-import/at-import.processor.ts:349]: increasing iterator here would be more easy to understand.

Comment (mertmit) [reply packages/nocodb/src/modules/jobs/jobs/at-import/at-import.processor.ts:349]: I've revised them for better readability
