### PR TITLE
fix: preloader fix in link modal

### LINKED ISSUE #6482: 🐛 Bug: Linked modal issues
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

- [x] Update table icon in sidenavbar
- [x] First time linked modal is opened - the skeleton is not seen. 
- [x] From links field we already know how many links are present - so only those many skeleton should be loaded.
- [x] The display value overflow in linked modal
image

### Desired Behavior

.

### Project Details

.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by sreehari2003**
## Change Summary

- closes #6482

Provide summary of changes with issue number if any.

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [x] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

### CODE REVIEW

File: packages/nc-gui/components/virtual-cell/components/ListChildItems.vue [hunk 1]
```diff
@@ -233,7 +242,7 @@ onKeyStroke('Escape', () => {
       </div>
     </template>
     <div
-      v-else
+      v-if="!isDataExist && !isChildrenLoading"
```
Comment (wingkwong) [inline packages/nc-gui/components/virtual-cell/components/ListChildItems.vue:245]: to make it more clean, you can just do in this way

```
v-else-if="!isChildrenLoading"
```

also you may think about the case like when `isDataExist` is `false` but `isChildrenLoading` is true.

File: packages/nc-gui/components/virtual-cell/components/ListChildItems.vue [hunk 2]
```diff
@@ -121,6 +123,13 @@ watch(expandedFormDlg, () => {
 onKeyStroke('Escape', () => {
   vModel.value = false
 })
+
+const isDataExist = computed(() => {
+  if (childrenList.value?.pageInfo?.totalRows || (isNew.value && state.value?.[colTitle.value]?.length)) {
+    return true
+  }
+  return false
```
Comment (wingkwong) [inline packages/nc-gui/components/virtual-cell/components/ListChildItems.vue:131]: if there is no extra logic in if-else block, you can directly return the value.

```ts
return childrenList.value?.pageInfo?.totalRows || (isNew.value && state.value?.[colTitle.value]?.length)
```

File: packages/nc-gui/components/virtual-cell/components/ListChildItems.vue [hunk 3]
```diff
@@ -49,6 +49,8 @@ const {
   displayValueProp,
 } = useLTARStoreOrThrow()
 
+isChildrenLoading.value = true
```
Comment (wingkwong) [inline packages/nc-gui/components/virtual-cell/components/ListChildItems.vue:52]: when will `isChildrenLoading` become `false`?

Comment (sreehari2003) [reply packages/nc-gui/components/virtual-cell/components/ListChildItems.vue:52]:
```typescript
  const loadChildrenList = async () => {
      try {
        isChildrenLoading.value = true
        if (colOptions.value.type === 'bt') return
        if (!rowId.value || !column.value) return
        if (isPublic.value) {
          childrenList.value = await $api.public.dataNestedList(
            sharedView.value?.uuid as string,
            encodeURIComponent(rowId.value),
            colOptions.value.type as 'mm' | 'hm',
            column.value.id,
            {
              limit: String(childrenListPagination.size),
              offset: String(childrenListPagination.size * (childrenListPagination.page - 1)),
              where:
                childrenListPagination.query && `(${relatedTableDisplayValueProp.value},like,${childrenListPagination.query})`,
            } as any,
            {
              headers: {
                'xc-password': sharedViewPassword.value,
              },
            },
          )
        } else {
          childrenList.value = await $api.dbTableRow.nestedList(
            NOCO,
            (project?.value?.id || (sharedView.value?.view as any)?.project_id) as string,
            meta.value.id,
            encodeURIComponent(rowId.value),
            colOptions.value.type as 'mm' | 'hm',
            column?.value?.id,
            {
              limit: String(childrenListPagination.size),
              offset: String(childrenListPagination.size * (childrenListPagination.page - 1)),
              where:
                childrenListPagination.query && `(${relatedTableDisplayValueProp.value},like,${childrenListPagination.query})`,
            } as any,
          )
        }
        childrenList.value?.list.forEach((row: Record<string, any>, index: number) => {
          isChildrenListLinked.value[index] = true
          isChildrenListLoading.value[index] = false
        })
        if (!childrenListPagination.query) {
          childrenListCount.value = childrenList.value?.pageInfo.totalRows ?? 0
        }
      } catch (e: any) {
        message.error(`${t('msg.error.failedToLoadChildrenList')}: ${await extractSdkResponseErrorMsg(e)}`)
      } finally {
        isChildrenLoading.value = false
      }
    }
```


there is a final block here

**Comment by sreehari2003** [comment]
https://github.com/nocodb/nocodb/assets/66205494/6da029e8-9c88-48a1-9a46-58f6169e4179

**Comment by sreehari2003** [comment]
image

File: packages/nc-gui/components/smartsheet/expanded-form/index.vue [hunk 4]
```diff
@@ -588,17 +592,21 @@ export default {
...
-    </div>
-  </NcModal>
+  <GeneralDeleteModal v-model:visible="showDeleteRowModal" entity-name="Record" :on-delete="() => onConfirmDeleteRowClick()">
+    <template #entity-preview>
+      <span>
+        <div class="flex flex-row items-center py-2.25 px-2.5 bg-gray-50 rounded-lg text-gray-700 mb-4">
+          <component :is="iconMap.table" class="nc-view-icon" />
+          <div
+            class="capitalize text-ellipsis overflow-hidden select-none w-full pl-1.75"
+            :style="{ wordBreak: 'keep-all', whiteSpace: 'nowrap', display: 'inline' }"
```
Comment (wingkwong) [inline packages/nc-gui/components/smartsheet/expanded-form/index.vue:602]: don't use `:style`... You can simply just add `break-keep whitespace-nowrap inline` to `class`.

File: packages/nc-gui/components/virtual-cell/components/ListChildItems.vue [hunk 5]
```diff
@@ -166,72 +170,70 @@ onKeyStroke('Escape', () => {
...
+          'h-[420px]': !isForm,
+          'h-[250px]': isForm,
+        }"
+        class="overflow-scroll nc-scrollbar-md cursor-pointer pr-1"
+      >
+        <template v-if="isChildrenLoading">
+          <div
+            v-for="(x, i) in Array.from({ length: 10 })"
+            :key="i"
+            class="!border-2 flex flex-row gap-2 mb-2 transition-all !rounded-xl relative !border-gray-200 hover:bg-gray-50"
```
Comment (wingkwong) [inline packages/nc-gui/components/virtual-cell/components/ListChildItems.vue:185]: for `<div>`, `!` seems not required. please double check.

File: packages/nc-gui/components/virtual-cell/components/ListChildItems.vue [hunk 6]
```diff
@@ -166,72 +170,70 @@ onKeyStroke('Escape', () => {
...
+            @expand="onClick(refRow)"
+            @click="
+              () => {
+                if (isPublic && !isForm) return
+                isNew
+                  ? unlinkRow(refRow, Number.parseInt(id))
+                  : isChildrenListLinked[Number.parseInt(id)]
+                  ? unlinkRow(refRow, Number.parseInt(id))
+                  : linkRow(refRow, Number.parseInt(id))
+              }
```
Comment (wingkwong) [inline packages/nc-gui/components/virtual-cell/components/ListChildItems.vue:231]: please move to a function if there is more than 1 action

File: packages/nc-gui/components/smartsheet/expanded-form/index.vue [hunk 7]
```diff
@@ -322,15 +323,18 @@ const onDeleteRowClick = () => {
...
-  showDeleteRowModal.value = false
-  await deleteRowById(primaryKey.value)
-  message.success('Row deleted')
-  if (!props.lastRow) {
-    await onNext()
-  } else if (!props.firstRow) {
-    emits('prev')
-  } else {
-    onClose()
+  try {
```
Comment (wingkwong) [inline packages/nc-gui/components/smartsheet/expanded-form/index.vue:326]: try block is actually for testing a block of code for errors. If you don't catch errors, basically there is no need to use. Besides, `deleteRowById` would trigger `$api` call. I think it's necessary to add a catch block here.

File: packages/nc-gui/components/virtual-cell/components/ListChildItems.vue [hunk 8]
```diff
@@ -166,72 +170,70 @@ onKeyStroke('Escape', () => {
...
+            :is-loading="isChildrenListLoading[Number.parseInt(id)]"
+            @expand="onClick(refRow)"
+            @click="
+              () => {
+                if (isPublic && !isForm) return
+                isNew
+                  ? unlinkRow(refRow, Number.parseInt(id))
+                  : isChildrenListLinked[Number.parseInt(id)]
+                  ? unlinkRow(refRow, Number.parseInt(id))
+                  : linkRow(refRow, Number.parseInt(id))
```
Comment (wingkwong) [inline packages/nc-gui/components/virtual-cell/components/ListChildItems.vue:230]: `parseInt` should be enough

File: packages/nc-gui/components/smartsheet/expanded-form/index.vue (hunk 7 above)
Comment (sreehari2003) [reply packages/nc-gui/components/smartsheet/expanded-form/index.vue:326]: in delete row by id the try catch already handled inside it

Comment (wingkwong) [reply packages/nc-gui/components/smartsheet/expanded-form/index.vue]: Got it. I misread the function with the same name in different store.

**Comment by dstala** [comment]
Screenshot 2023-09-28 at 11 57 45 PM

File: packages/nc-gui/components/virtual-cell/components/ListChildItems.vue [hunk 9]
```diff
@@ -121,6 +123,39 @@ watch(expandedFormDlg, () => {
 onKeyStroke('Escape', () => {
   vModel.value = false
 })
+
+const skeltonAmountToShow = ref(childrenListCount.value === 0 ? 10 : childrenListCount.value)
```
Comment (mustafapc19) [inline packages/nc-gui/components/virtual-cell/components/ListChildItems.vue:127]: Make this a computed and better name for this would be skeltonCount

File: packages/nc-gui/components/virtual-cell/components/ListChildItems.vue [hunk 10]
```diff
@@ -121,6 +123,39 @@ watch(expandedFormDlg, () => {
...
+})
+
+const isDataExist = computed<boolean>(() => {
+  return childrenList.value?.pageInfo?.totalRows || (isNew.value && state.value?.[colTitle.value]?.length)
+})
+
+const linkOrUnLink = (rowRef: Record<string, string>, id: string) => {
+  if (isPublic.value && !isForm.value) return
+  isNew.value
+    ? unlinkRow(rowRef, parseInt(id))
```
Comment (mustafapc19) [inline packages/nc-gui/components/virtual-cell/components/ListChildItems.vue:154]: Remove nested ternary condition and use simple if with early return

File: packages/nc-gui/components/virtual-cell/components/ListChildItems.vue [hunk 11]
```diff
@@ -166,72 +199,61 @@ onKeyStroke('Escape', () => {
...
-                    <a-skeleton-input class="!h-4 !w-24" active size="small" />
-                  </div>
-                  <div class="flex flex-col gap-0.5">
-                    <a-skeleton-input class="!h-4 !w-12" active size="small" />
-                    <a-skeleton-input class="!h-4 !w-24" active size="small" />
-                  </div>
+    <div v-if="isDataExist || isChildrenLoading" class="mt-2 mb-2">
+      <div
+        :class="{
+          'h-[420px]': !isForm,
```
Comment (mustafapc19) [inline packages/nc-gui/components/virtual-cell/components/ListChildItems.vue:205]: Convert to tailwind standard unit

File: packages/nc-gui/components/virtual-cell/components/ListChildItems.vue [hunk 12]
```diff
@@ -166,72 +199,61 @@ onKeyStroke('Escape', () => {
...
+        class="overflow-scroll nc-scrollbar-md cursor-pointer pr-1"
+      >
+        <template v-if="isChildrenLoading">
+          <div
+            v-for="(x, i) in Array.from({ length: skeltonAmountToShow })"
+            :key="i"
+            class="border-2 flex flex-row gap-2 mb-2 transition-all rounded-xl relative border-gray-200 hover:bg-gray-50"
+          >
+            <a-skeleton-image class="h-24 w-24 !rounded-xl" />
+            <div class="flex flex-col m-[.5rem] gap-2 flex-grow justify-center">
```
Comment (mustafapc19) [inline packages/nc-gui/components/virtual-cell/components/ListChildItems.vue:217]: Convert `m-[.5rem]` to tailwind standard unit

File: packages/nc-gui/components/virtual-cell/components/ListItems.vue [hunk 13]
```diff
@@ -268,7 +270,10 @@ onKeyStroke('Escape', () => {
         </div>
       </div>
     </template>
-    <div v-else class="py-2 h-[420px] flex flex-col gap-3 items-center justify-center text-gray-500">
+    <div
+      v-if="!isChildrenExcludedLoading && !childrenExcludedList?.pageInfo?.totalRows"
+      class="py-2 h-[420px] flex flex-col gap-3 items-center justify-center text-gray-500"
```
Comment (mustafapc19) [inline packages/nc-gui/components/virtual-cell/components/ListItems.vue:275]: Move `h-[420px]` to tailwind standard class

File: packages/nc-gui/components/smartsheet/expanded-form/index.vue [hunk 14]
```diff
@@ -3,7 +3,7 @@ import type { TableType, ViewType } from 'nocodb-sdk'
 import { isLinksOrLTAR, isSystemColumn, isVirtualCol } from 'nocodb-sdk'
 import type { Ref } from 'vue'
 import MdiChevronDown from '~icons/mdi/chevron-down'
-import TableIcon from '~icons/nc-icons/table'
+import RecordIcon from '~icons/nc-icons/record'
```
Comment (mustafapc19) [inline packages/nc-gui/components/smartsheet/expanded-form/index.vue:6]: Move this to general icon and use GeneralIcon in this component

File: packages/nc-gui/components/virtual-cell/components/ListChildItems.vue [hunk 15]
```diff
@@ -18,7 +18,13 @@ import {
   useVModel,
 } from '#imports'
 
-const props = defineProps<{ modelValue?: boolean; cellValue: any; column: any }>()
+interface Iprop {
```
Comment (wingkwong) [inline packages/nc-gui/components/virtual-cell/components/ListChildItems.vue:21]: call it `Props` - keep the naming consistent with other files.

File: packages/nc-gui/components/virtual-cell/components/ListChildItems.vue [hunk 16]
```diff
@@ -150,11 +154,13 @@ const isDataExist = computed<boolean>(() => {
...
   if (isPublic.value && !isForm.value) return
-  isNew.value
-    ? unlinkRow(rowRef, parseInt(id))
-    : isChildrenListLinked.value[parseInt(id)]
-    ? unlinkRow(rowRef, parseInt(id))
-    : linkRow(rowRef, parseInt(id))
+  if (isNew.value) {
+    unlinkRow(rowRef, parseInt(id))
+  } else if (isChildrenListLinked.value[parseInt(id)]) {
+    unlinkRow(rowRef, parseInt(id))
```
Comment (wingkwong) [inline packages/nc-gui/components/virtual-cell/components/ListChildItems.vue:160]: same logic - you can move this condition to the first one, i.e.

```ts
if (isNew.value || isChildrenListLinked.value[parseInt(id)]) {
```

File: packages/nc-gui/components/virtual-cell/components/ListChildItems.vue [hunk 17]
```diff
@@ -124,23 +130,21 @@ onKeyStroke('Escape', () => {
...
 /* 
    to render same number of skelton as the number of cards
    displayed
  */
-watch(childrenListPagination, () => {
+
+const skeltonCount = computed(() => {
   if (childrenListCount.value < 10 && childrenListPagination.page === 1) {
-    skeltonAmountToShow.value = childrenListCount.value === 0 ? 10 : childrenListCount.value
+    return childrenListCount.value === 0 ? 10 : childrenListCount.value
```
Comment (wingkwong) [inline packages/nc-gui/components/virtual-cell/components/ListChildItems.vue:140]:
```ts
return childrenListCount.value || 10
```

File: packages/nc-gui/components/virtual-cell/components/ListChildItems.vue [hunk 18]
```diff
@@ -124,23 +130,21 @@ onKeyStroke('Escape', () => {
...
 
-const skeltonAmountToShow = ref(childrenListCount.value === 0 ? 10 : childrenListCount.value)
-
 /* 
    to render same number of skelton as the number of cards
    displayed
  */
-watch(childrenListPagination, () => {
+
+const skeltonCount = computed(() => {
```
Comment (wingkwong) [inline packages/nc-gui/components/virtual-cell/components/ListChildItems.vue:138]: please fix the variable typo -> `totlaRows`

File: packages/nc-gui/components/virtual-cell/components/ListChildItems.vue [hunk 19]
```diff
@@ -124,23 +130,21 @@ onKeyStroke('Escape', () => {
...
   }
-
   const totlaRows = Math.ceil(childrenListCount.value / 10)
 
   if (totlaRows === childrenListPagination.page) {
-    skeltonAmountToShow.value = childrenListCount.value % 10
+    return childrenListCount.value % 10
   } else {
-    skeltonAmountToShow.value = 10
+    return 10
```
Comment (wingkwong) [inline packages/nc-gui/components/virtual-cell/components/ListChildItems.vue:147]: you don't need `else` here.

File: packages/nc-gui/utils/iconUtils.ts [hunk 20]
```diff
@@ -235,6 +235,7 @@ import MaterialSymbolsBlock from '~icons/material-symbols/block'
 } as const */
 
 export const iconMap = {
+  recordIcon: RecordIcon,
```
Comment (wingkwong) [inline packages/nc-gui/utils/iconUtils.ts:238]: following the naming pattern

```ts
record: RecordIcon,
```

File: packages/nc-gui/components/virtual-cell/components/ListChildItems.vue (hunk 17 above)
Comment (sreehari2003) [reply packages/nc-gui/components/virtual-cell/components/ListChildItems.vue:140]: one doubt  , how does this work ? 

if   ``` childrenListCount.value ``` === 0 it will return 0 right ? but we need 10 there.

Comment (wingkwong) [reply packages/nc-gui/components/virtual-cell/components/ListChildItems.vue]: > one doubt , how does this work ?

`||` is OR operator, which uses the right value if left one is [falsy](https://developer.mozilla.org/en-US/docs/Glossary/Falsy). if `a === 0`, then `a || 10 -> 10`.
On the other hand, the nullish coalescing operator `??` uses the right value if left one is `null` or `undefined`. If `a === 0`, then `a ?? 10 -> 0`. If `a === null / undefined`, then `a ?? 10 -> 10`.

> if childrenListCount.value === 0 it will return 0 right ? but we need 10 there.

It returns 10.

File: packages/nc-gui/components/smartsheet/expanded-form/index.vue [hunk 21]
```diff
@@ -324,15 +324,9 @@ const onDeleteRowClick = () => {
 const onConfirmDeleteRowClick = async () => {
   showDeleteRowModal.value = false
   await deleteRowById(primaryKey.value)
-  message.success('Row deleted')
```
Comment (wingkwong) [inline packages/nc-gui/components/smartsheet/expanded-form/index.vue:327]: double check if this `message.success` is no longer required so deleted by mistake.

**Comment by sreehari2003** [comment]
https://github.com/nocodb/nocodb/issues/6520
