### PR TITLE
fix(nc-gui): project state not properly reset 

### LINKED ISSUE #3635: new project displays deleted project table name's
Node: **v16.14.0**
Arch: **arm64**
Platform: **darwin**
Docker: **false**
Database: **sqlite3**
ProjectOnRootDB: **true**
RootDB: **sqlite3**
PackageVersion: **0.96.4**

also observed in pg/pg
also observed with disabled cache

- create project
- add table `Sheet1`
- delete project
- create a new project
- table tree view displays `Sheet1`

### PR DESCRIPTION
**Pull request by bcakmakoglu**
## Change Summary

* fixes #3635 
* only load project if no request is running already
* move fetching project to parent page to prevent multiple loads
* defer subpages until project is loaded
   * show spinner when loading
* reset state when page is unmounted

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [x] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

### CODE REVIEW

File: packages/nc-gui/composables/useProject.ts [hunk 1]
```diff
@@ -1,31 +1,53 @@
...
+} from '#imports'
+import type { ProjectMetaInfo, Roles } from '~/lib'
 import type { ThemeConfig } from '@/composables/useTheme'
-import { createEventHook, useInjectionState } from '#imports'
 
 const [setup, use] = useInjectionState((_projectId?: MaybeRef<string>) => {
-  const { $api, $e } = useNuxtApp()
+  const { $e } = useNuxtApp()
+
+  const { api, isLoading } = useApi()
```
Comment (pranavxc) [inline packages/nc-gui/composables/useProject.ts:25]: You are using the same `api` reference for loading the table list as well, so if you try to reload the table list(context menu in the tree view) it may lead to some issues I think.

Comment (bcakmakoglu) [reply packages/nc-gui/composables/useProject.ts:25]: What's the difference between using `$api` and `api` in this case though?
It would still be only one api instance that's used to fetch the data, regardless if it's the global one or a new one locally.

If there is/was an issue with the reload, it was a pre-existing condition 😄

Comment (pranavxc) [reply packages/nc-gui/composables/useProject.ts:25]: > What's the difference between using `$api` and `api` in this case though? It would still be only one api instance that's used to fetch the data, regardless if it's the global one or a new one locally.
> 
> If there is/was an issue with the reload, it was a pre-existing condition 😄

We are using the `isLoading` variable for toggling between loader and spinner.

```vue
 <div class="w-full min-h-[300px] flex-auto">
        <NuxtPage v-if="!isLoadingProject" />
        <div v-else class="w-full h-full flex justify-center items-center">
          <a-spin size="large" />

```

Comment (bcakmakoglu) [reply packages/nc-gui/composables/useProject.ts:25]: global isLoading is *always* triggered if an api instance does a request.

So if `const { isLoading } = useApi()` is `true` then `const { isLoading } = useGlobal()` is true as well, at least that is the intended way ^^

Comment (mertmit) [reply packages/nc-gui/composables/useProject.ts:25]: I can also confirm I used useNuxtApp -> $api to not trigger isLoading state while using API. (on project list page, color picker api, as pageLoading for every call was not ideal)

Comment (pranavxc) [reply packages/nc-gui/composables/useProject.ts:25]: I think earlier I'd used `useApi()` only for loading project and for rest of them the global `$api` is used

Comment (bcakmakoglu) [reply packages/nc-gui/composables/useProject.ts:25]: As I suspected, the issue(s) come from something else. Will push changes in a bit ^^

**Review by dstala — APPROVED** [review]

File: packages/nc-gui/composables/useProject.ts (hunk 1 above)
Comment (bcakmakoglu) [reply packages/nc-gui/composables/useProject.ts:25]: Fix pushed, I had to play around a bit to get it right
* Subpages should now wait (and show a spinner) until the parent pages are done fetching the project/tables etc.
* The reload issue in the video came from using `v-if` on a NuxtPage component, which doesn't work, when the condition turns from true to false, it crashes the app
