### PR TITLE
fix: map PostgreSQL 'double precision' correctly as 'float'

### LINKED ISSUE #8337: 🐛 Bug:  postgres float8 not recognized as a 'numeric' field.
### Please confirm if bug report does NOT exist already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Create a postgres db with a table with a float8 column
2. Add the db as a data source to a nocodb instance
Note that nocodb interprets it to be a Single Line Text field.

### Desired Behavior

It should be treated as a Decimal ui field.

### Project Details

Node: **v20.11.1**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **pg**
PackageVersion: **0.205.1**

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by maheshdhoran**
## Change Summary
Fixes https://github.com/nocodb/nocodb/issues/8337

Corrected the data type mapping for PostgreSQL 'double precision' from 'string' to 'float'.

## Change type
- [X] fix: (bug fix for the user, not a fix to a build script)

## Summary by CodeRabbit

- **Refactor**
  - Enhanced data type handling for 'double precision' to improve accuracy and performance in database interactions.

### CODE REVIEW

File: packages/nocodb-sdk/src/lib/sqlUi/PgUi.ts [hunk 1]
```diff
@@ -1436,7 +1436,7 @@ export class PgUi {
       case 'daterange':
         return 'string';
       case 'double precision':
-        return 'string';
+        return 'float';
```
Comment (mertmit) [inline packages/nocodb-sdk/src/lib/sqlUi/PgUi.ts:1439]: Please merge this case with float4, float8 as you've within ModelXcMetaPg.ts too keep it consistent.

File: packages/nocodb/src/db/sql-mgr/code/models/xc/ModelXcMetaPg.ts [hunk 2]
```diff
@@ -114,7 +114,7 @@ class ModelXcMetaPg extends BaseModelXcMeta {
         str = 'date';
         break;
       case 'double precision':
-        str = 'double';
+        str = 'float';
```
Comment (mertmit) [inline packages/nocodb/src/db/sql-mgr/code/models/xc/ModelXcMetaPg.ts:117]: This function is legacy and not used in recent versions, please revert this part as it is not required or applicable.

**Review by mertmit — CHANGES_REQUESTED** [review]

**Comment by mertmit** [comment]
As a side note, please move `closes #8337` from title to body, that way Github will automatically link your PR with the issue.

**Comment by maheshdhoran** [comment]
> As a side note, please move `closes #8337` from title to body, that way Github will automatically link your PR with the issue.

Done

**Review by mertmit — APPROVED** [review]
