### PR TITLE
Autocomplete Email Login & Signup

### LINKED ISSUE #6241: 🐛 Bug: Login e-mail form field is not autocompleted
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Open your NocoDB login page (`https://YOUR.DOMAIN/dashboard/#/signin`).

2. Click in the e-mail field and press <kbd>↓</kbd> (arrow down) on your keyboard. No list with previously entered e-mail addresses appears.

### Desired Behavior

In step 2 above, a list with previously entered e-mail addresses should be displayed.

For this, the `<input>` element of the e-mail address field on the login page should be changed to have the attributes [**`type="email"`**](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email) (currently it has `type="text"`, see screenshot below) as well as [**`autocomplete="email"`**](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#autocomplete).

Besides, the `<input>` element of the *password* field should have [**`autocomplete="current-password"`**](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete) (it already has the proper `type="password"`).

### Project Details

Node: **v16.20.1**
Arch: **x64**
Platform: **linux**
Docker: **false**
RootDB: **sqlite3**
PackageVersion: **0.111.0**

### Attachments

Current `<input>` element of the e-mail address field on the login page:

Bildschirmfoto vom 2023-08-26 13-49-01

### PR DESCRIPTION
**Pull request by DarkPhoenix2704**
## Change Summary

Provide summary of changes with issue number if any.

Closes #6241 

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [ ] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

### CODE REVIEW

File: packages/nc-gui/pages/signin.vue [hunk 1]
```diff
@@ -101,19 +101,23 @@ function resetError() {
...
                 :placeholder="$t('msg.info.signUp.workEmail')"
                 @focus="resetError"
               />
             </a-form-item>
 
-            <a-form-item :label="$t('labels.password')" name="password" :rules="formRules.password">
+            <a-form-item :label="$t('labels.password')" name="password" :rules="formRules.password" aria-autocomplete="password">
               <a-input-password
                 v-model:value="form.password"
+                type="password"
```
Comment (wingkwong) [inline packages/nc-gui/pages/signin.vue:119]: I don't think this line is required since you are using `<a-input-password />`

**Review by wingkwong — COMMENTED** [review]
Please double check the values for `aria-autocomplete`. From below docs, it seems the expected value is either `inline`, `list`, `both` or `none`.

refs:
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-autocomplete
- https://www.w3.org/TR/wai-aria-1.1/#aria-autocomplete

File: packages/nc-gui/pages/signin.vue [hunk 2]
```diff
@@ -114,6 +116,7 @@ function resetError() {
             <a-form-item :label="$t('labels.password')" name="password" :rules="formRules.password">
               <a-input-password
                 v-model:value="form.password"
+                autocomplete="password"
```
Comment (salim-b) [inline packages/nc-gui/pages/signin.vue:119]: According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#values), `autocomplete="password"` is not valid. It can either be `"new-password"` or `"current-password"`.

In this case it should be **`autocomplete="current-password"`**.

**Comment by wingkwong** [comment]
@DarkPhoenix2704 please click re-request review once it is ready. Otherwise, I'll assume this PR is still WIP.

**Review by wingkwong — APPROVED** [review]
