### PR TITLE
fix(upstall): kvstore init

### LINKED ISSUE #10159: 🐛 Bug: Auto Upstall fails reinstall
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

* Install NocoDB using Auto Upstall
* Observe NocoDB is running using web browser
* Stop NocoDB using management panel
* Exit management panel
* Reinstall NocoDB using Auto Upstall without deleting the nocodb directory
* Observe repeated authentication errors in database log using management panel
* Observe 404 Not found or Bad Gateway using web browser

Verify reinstall works if nocodb directory is deleted:
* Stop NocoDB using management panel
* Exit management panel
* rm -r nocodb 
* Install NocoDB using Auto Upstall
* Observe NocoDB is running using web browser

### Desired Behavior

Successfully reinstall NocoDB without deleting the nocodb directory, which may contain user content.  

### Project Details

NocoDB 0.258.11 installed using Auto Upstall 12/31/24.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by sinanmohd**
## Change Summary

this pr introduces a key value store in pure posix shell to store the upstall state 
and a state version for future migrations 

closes #10159

## Change type
- [x] fix: (bug fix for the user, not a fix to a build script)

## Tests

tested on Ubuntu 22.04.3 LTS

### CODE REVIEW

File: docker-compose/1_Auto_Upstall/noco.sh [hunk 1]
```diff
@@ -94,7 +200,12 @@ urlencode() {
 }
 
 generate_password() {
-	openssl rand -base64 48 | tr -dc 'a-zA-Z0-9_+*' | head -c 32
+	if ! pass="$(kvstore_get getval generated_password)"; then
+		pass="$(tr -dc A-Za-z0-9 </dev/urandom | head -c 32)"
+		kvstore_set generated_password "$pass"
```
Comment (pranavxc) [inline docker-compose/1_Auto_Upstall/noco.sh:205]: Is it safe to store the password in the store(file)?

Comment (sinanmohd) [reply docker-compose/1_Auto_Upstall/noco.sh:205]: yes

**Review by pranavxc — APPROVED** [review]
