### PR TITLE
fix: Load JWT secret from store on app init

### LINKED ISSUE #5679: 🐛 Bug: after updated (docker) to 0.107.0 I get multiple errors
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

Update a working container in 0.106.1 to 0.107.0

Once it boots up again, even I can log in, I get this error:
ERROR [n] Malformed UTF-8 data
Error: Malformed UTF-8 data
    at Object.stringify (/usr/src/app/node_modules/crypto-js/core.js:523:24)
    at WordArray.init.toString (/usr/src/app/node_modules/crypto-js/core.js:278:38)
    at f.getConnectionConfig (/usr/src/app/docker/main.js:1:756558)
    at Function.get (/usr/src/app/docker/main.js:1:1266343)
    at b.getDataList (/usr/src/app/docker/main.js:1:1119421)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async b.dataList (/usr/src/app/docker/main.js:1:1117708)
    at async p.dataList (/usr/src/app/docker/main.js:1:52716)

after a while, also this one:
ERROR [n] Invalid refresh token
Error: Invalid refresh token
    at Function.badRequest (/usr/src/app/docker/main.js:1:646501)
    at S.refreshToken (/usr/src/app/docker/main.js:1:1228807)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async P.refreshToken (/usr/src/app/docker/main.js:1:175256)
    at async /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at async /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:17

and then when navigating:
ERROR [n] Cannot GET /favicon.ico
NotFoundException: Cannot GET /favicon.ico
    at callback (/usr/src/app/node_modules/@nestjs/core/router/routes-resolver.js:77:19)
    at /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:23
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:328:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:280:10)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:136:14)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:140:7)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:140:7)

### Desired Behavior

Everything continues working as expected.

### Project Details

Node: **v16.19.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **mysql2**
PackageVersion: **0.107.0**

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by pranavxc**
## Change Summary

- [x] On app init load jwt secret from the store table
- [x] Move app init to a provider

fixes #5679

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [x] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

### CODE REVIEW

File: packages/nocodb/src/Noco.ts [hunk 1]
```diff
@@ -125,4 +133,56 @@ export default class Noco {
...
+          process.env.NC_JWT_EXPIRES_IN ?? '10h';
+      }
+    }
+    let serverId = (
+      await Noco._ncMeta.metaGet('', '', 'nc_store', {
+        key: 'nc_server_id',
+      })
+    )?.value;
+    if (!serverId) {
+      await Noco._ncMeta.metaInsert('', '', 'nc_store', {
```
Comment (wingkwong) [inline packages/nocodb/src/Noco.ts:166]: `'nc_store'` -> `MetaTable.STORE`

**Review by wingkwong — APPROVED** [review]
