### PR TITLE
fix: compose configuration generation

### LINKED ISSUE #9533: 🐛 Bug: noco.sh generates invalid docker-compose.yml file
### Please confirm that the bug report does ***not*** already exist

- [X] I confirm there is no existing issue for this bug.

### Steps to reproduce

Running the installer and choosing the following options:

```
Enter the IP address or domain name for the NocoDB instance (default: 100.100.100.100):
Show Advanced Options? [y/N]: y
Choose Community or Enterprise Edition [CE/EE] (default: CE):
Do you want to enable Redis for caching? [Y/n]:
Do you want to enable Minio for file storage? [Y/n]: n
Do you want to enable Watchtower for automatic updates? [Y/n]: n
How many instances of NocoDB do you want to run? (1-2) [1]: 1
```

output:
```
yaml: unmarshal errors:
  line 72: mapping key "networks" already defined at line 69
```

### Desired Behavior

The error above occurs because the `redis` service in the `docker-compose.yml` file has a duplicate `networks` key.
This shouldn't happen. The bug is located in the [noco.sh](https://github.com/nocodb/nocodb/blob/25352e96cc0559a8bcc8561c6f1a5896cf571cee/docker-compose/1_Auto_Upstall/noco.sh) script.

### Project Details

NocoDB used as docker: true

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by sinanmohd**
## Change Summary
- closes #9533 
${parameter:+word} always expands word when parameter is set

## Change type
- [x] fix: compose configuration generation

## Test/ Verification
validated with docker bin
docker compose config > /dev/null; echo $?
> 0

### CODE REVIEW

File: docker-compose/1_Auto_Upstall/noco.sh [hunk 1]
```diff
@@ -496,11 +496,20 @@ generate_credentials() {
 
 create_docker_compose_file() {
 
-  image="nocodb/nocodb:latest"
+    if [ "${CONFIG_EDITION}" = "EE" ] || [ "${CONFIG_EDITION}" = "ee" ]; then
+        image="nocodb/ee:latest"
```
Comment (o1lab) [inline docker-compose/1_Auto_Upstall/noco.sh:500]: nocodb/nocodb-ee

Comment (o1lab) [reply docker-compose/1_Auto_Upstall/noco.sh:500]: https://hub.docker.com/r/nocodb/nocodb-ee

**Review by pranavxc — APPROVED** [review]
