### PR TITLE
fix: Disable button to avoid duplicate api call when creating column, project and table

### LINKED ISSUE #5158: 🐛 Bug: clicking save button multiple times on "new column" or "edit column" will fire multiple queries
### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Steps to reproduce ?

1. Use a table with millions of rows that will take a few seconds to load a page of 25 elements.
2. Edit a column or save a new column.
3. Click the "save" button multiple times.  Each time will fire a query.

If the queries are expensive and enough are fired, it can cause the UI to timeout.

### Desired Behavior

The button should be disabled to prevent multiple duplicate queries.

### Project Details

Node: **v16.17.1**
Arch: **x64**
Platform: **linux**
Docker: **true**
RootDB: **sqlite3**
PackageVersion: **0.105.2**

### Attachments

Screenshot 2023-02-19 at 11 49 19 AM

### PR DESCRIPTION
**Pull request by pranavxc**
## Change Summary

close #5158

## Change type

- [ ] feat: (new feature for the user, not a new feature for build script)
- [x] fix: (bug fix for the user, not a fix to a build script)
- [ ] docs: (changes to the documentation)
- [ ] style: (formatting, missing semi colons, etc; no production code change)
- [ ] refactor: (refactoring production code, eg. renaming a variable)
- [ ] test: (adding missing tests, refactoring tests; no production code change)
- [ ] chore: (updating grunt tasks etc; no production code change)

## Test/ Verification

Provide summary of changes.

## Additional information / screenshots (optional)

Anything for maintainers to be made aware of

### CODE REVIEW

File: packages/nc-gui/components/dlg/TableCreate.vue [hunk 1]
```diff
@@ -78,14 +78,18 @@ const systemColumnsCheckboxInfo = SYSTEM_COLUMNS.map((c, index) => ({
...
 const _createTable = async () => {
   try {
+    creating.value = true
     await validate()
   } catch (e: any) {
     e.errorFields.map((f: Record<string, any>) => message.error(f.errors.join(',')))
     if (e.errorFields.length) return
   }
   await createTable()
+  creating.value = false
```
Comment (wingkwong) [inline packages/nc-gui/components/dlg/TableCreate.vue:92]: This line should be put inside `finally` block so that it will set to `false` even there is an error. Otherwise, users  cannot resubmit like below.

image

File: packages/nc-gui/pages/index/index/create.vue [hunk 2]
```diff
@@ -48,6 +52,7 @@ const createProject = async () => {
   } catch (e: any) {
     message.error(await extractSdkResponseErrorMsg(e))
   }
+  creating.value = false
```
Comment (wingkwong) [inline packages/nc-gui/pages/index/index/create.vue:55]: even though this line is working fine, I'd prefer to put it in `finally` block as well since it starts in `try` block.

**Review by wingkwong — CHANGES_REQUESTED** [review]

**Review by dstala — APPROVED** [review]

**Review by wingkwong — APPROVED** [review]
